### ISSUE TITLE
[help request] virtual/bootloader

### ISSUE THREAD

**Issue by modjo756** [modjo756/meta-seco#1]
Hi @graugans , @drewmoseley  i hope all is okay for you (since the time) !
i need your help about a layer that i made for the secoA62 card. I'm trying to build an image on rocko branch but i have an error with virtual/bootloader that i can't resolve for the moment. You can find my layer here : [https://github.com/modjo756/meta-seco/tree/rocko](meta-seco).
For the moment i use the seco u-boot/kernel (like this i can dialog with seco support).
The problem is when i want to build u-boot : 

_$ bitbake virtual/bootloader_

i have this error : 

_### Nothing PROVIDES 'virtual/bootloader'
u-boot-compulab PROVIDES virtual/bootloader but was skipped: incompatible with machine secosbca62 (not in COMPATIBLE_MACHINE)
u-boot-variscite PROVIDES virtual/bootloader but was skipped: You cannot use UBOOT_MACHINE and UBOOT_CONFIG at the same time.
u-boot-gateworks-imx PROVIDES virtual/bootloader but was skipped: incompatible with machine secosbca62 (not in COMPATIBLE_MACHINE) ..._

In my layer conf i added machine conf that define 

_### PREFERRED_PROVIDER_u-boot ??= "u-boot-seco"
PREFERRED_PROVIDER_virtual/bootloader ??="u-boot-seco"
PREFERRED_VERSION_u-boot-seco = "2015.04"_

I can build the kernel with virtual/kernel but not u-boot ! Do you have an idea how to resolve this please ?

**Comment by drewmoseley** [comment]
Does the u-boot-seco recipe have:
`PROVIDES = "virtual/bootloader"`

**Comment by modjo756** [comment]
You are right, i added this on u-boot-seco, but now i have this error : 
_u-boot-seco PROVIDES virtual/bootloader but was skipped: You cannot use UBOOT_MACHINE and UBOOT_CONFIG at the same time._
I need to look what is this variables ...

**Comment by modjo756** [comment]
@drewmoseley , thanks for your tip now i can build u-boot but i have another error when i try to build my image : 

_ERROR: Nothing RPROVIDES 'virtual/bootloader' (but /media/mls/data/seco/yocto-rocko/sources/poky/meta/recipes-core/packagegroups/packagegroup-base.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'virtual/bootloader' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['virtual/bootloader']
NOTE: Runtime target 'packagegroup-distro-base' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-distro-base', 'virtual/bootloader']
NOTE: Runtime target 'packagegroup-base-wifi' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-base-wifi', 'virtual/bootloader']
NOTE: Runtime target 'packagegroup-base-alsa' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-base-alsa', 'virtual/bootloader']
NOTE: Runtime target 'packagegroup-base-usbgadget' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-base-usbgadget', 'virtual/bootloader']
NOTE: Runtime target 'packagegroup-base-nfc' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-base-nfc', 'virtual/bootloader']
NOTE: Runtime target 'packagegroup-base-nfs' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-base-nfs', 'virtual/bootloader']
NOTE: Runtime target 'packagegroup-base-3g' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-base-3g', 'virtual/bootloader']
NOTE: Runtime target 'packagegroup-base-usbhost' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-base-usbhost', 'virtual/bootloader']
ERROR: Required build target 'seco-image-qt5' has no buildable providers.
Missing or unbuildable dependency chain was: ['seco-image-qt5', 'packagegroup-base-usbhost', 'virtual/bootloader']_

It's look like a problem with the bblayers.conf but i didn't find the error, see under my file : 

_LCONF_VERSION = "7"

BBPATH = "${TOPDIR}"
BSPDIR := "${@os.path.abspath(os.path.dirname(d.getVar('FILE', True)) + '/../..')}"

BBFILES ?= ""
BBLAYERS = " \
  ${BSPDIR}/sources/poky/meta \
  ${BSPDIR}/sources/poky/meta-poky \
  \
  ${BSPDIR}/sources/meta-openembedded/meta-oe \
  ${BSPDIR}/sources/meta-openembedded/meta-multimedia \
  ${BSPDIR}/sources/meta-openembedded/meta-python \
  ${BSPDIR}/sources/meta-openembedded/meta-networking \
  ${BSPDIR}/sources/meta-openembedded/meta-webserver \
  \
  ${BSPDIR}/sources/meta-freescale \
  ${BSPDIR}/sources/meta-freescale-3rdparty \
  ${BSPDIR}/sources/meta-freescale-distro \
  \
  ${BSPDIR}/sources/meta-qt5 \
  ${BSPDIR}/sources/meta-seco \
  \
"_

An idea ?

**Comment by modjo756** [comment]
Problem solved, remove virtual/bootloader from MACHINE_EXTRA_RRECOMMENDS ...
